Repository hashicorp/terraform-provider-archive, pull requests merged in 2023-03, with the labels that each got.

#200 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-141529.yaml
  README.md
  go.mod
Labels: dependencies, size/XS, go

#202 .github/workflows: Test on Terraform 1.4.* versions
  .github/workflows/test.yml
Labels: size/XS

#203 Migrate acceptance tests to terraform-plugin-testing
  go.mod
  go.sum
  internal/provider/data_source_archive_file_test.go
  internal/provider/resource_archive_file_test.go
Labels: dependencies, size/XS, technical-debt
