Repository hashicorp/terraform-provider-archive, pull requests merged in 2023-01, with the labels that each got.

#174 .github/workflows: Pin actions versions to SHAs
  .github/workflows/add-content-to-project.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: size/S

#176 Update setup-go to use `go.mod`
  .github/workflows/release.yml
  .github/workflows/test.yml
  .go-version
Labels: size/XS

#180 ci: merging `golangci-lint` rules
  .golangci.yml
Labels: size/XS

#179 Add Jira automation
  .github/workflows/jira-sync.yml
  .github/workflows/send-to-jira.yml
Labels: size/M

#165 Add more hash outputs of archive content
  docs/data-sources/file.md
  docs/resources/file.md
  internal/provider/data_source_archive_file.go
  internal/provider/data_source_archive_file_test.go
  internal/provider/resource_archive_file.go
  internal/provider/resource_archive_file_test.go
Labels: size/L, tf-devex-triage
