Repository hashicorp/terraform-provider-archive, pull requests merged in 2024-01, with the labels that each got.

#293 cdktf: update documentation
  docs/cdktf/python/data-sources/file.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/file.md
  docs/cdktf/typescript/data-sources/file.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/file.md
Labels: size/S

#299 cdktf: update documentation
  docs/cdktf/python/data-sources/file.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/file.md
  docs/cdktf/typescript/data-sources/file.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/file.md
Labels: size/XS

#298 Fix generation of archives when using exclude_symlink_directories
  .changes/unreleased/BUG FIXES-20240115-101358.yaml
  .changes/unreleased/BUG FIXES-20240115-101510.yaml
  .changes/unreleased/BUG FIXES-20240117-101851.yaml
  .changes/unreleased/BUG FIXES-20240117-101923.yaml
  internal/provider/data_source_archive_file_test.go
  internal/provider/resource_archive_file_test.go
  internal/provider/zip_archiver.go
  internal/provider/zip_archiver_test.go
Labels: bug, size/XL

#302 Bumping ghaction-terraform-provider-release to v3.0.0
  .github/workflows/release.yml
Labels: dependencies, size/XS

#303 Bumping ghaction-terraform-provider-release to v3.0.1
  .changes/2.4.2.md
  .changes/unreleased/BUG FIXES-20240115-101358.yaml
  .changes/unreleased/BUG FIXES-20240115-101510.yaml
  .changes/unreleased/BUG FIXES-20240117-101851.yaml
  .changes/unreleased/BUG FIXES-20240117-101923.yaml
  .github/workflows/release.yml
  CHANGELOG.md
Labels: dependencies, size/S

#307 Added GHA dependabot config for managing hashicorp actions
  .github/dependabot.yml
Labels: dependencies, size/XS
