Repository hashicorp/terraform-provider-archive, pull requests merged in 2025-05, with the labels that each got.

#430 Prepare for 2.7.1 Release
  .changes/2.7.1.md
  CHANGELOG.md
  version/VERSION
Labels: size/XS

#431 Add catalog metadata (META.d)
  .copywrite.hcl
  META.d/_summary.yaml
Labels: size/XS

#432 chore: CRT Final Onboarding
  .copywrite.hcl
  .github/workflows/release.yml
  .goreleaser.yml
  README.md
Labels: size/L

#434 github: Use Dependabot to keep Actions updated
  .github/dependabot.yml
Labels: dependencies, size/XS

#438 Create pull_request_template.md
  .github/pull_request_template.md
Labels: size/XS
